### ISSUE TITLE
biblatex support

### ISSUE THREAD

**Issue by dgalcius** [vtex-soft/texsupport.elsevier-book#1]
author:

> book class template uses the _natbib_ package by default. 

 
> We want to use the _biblatex_ package (with _biber_ instead of bibtex)
> instead because it is much more flexible and modern,
> and it supports _separate bibliographies in each chapter._

**Comment by katyhuff** [comment]
@dgalcius (another author here) In the current template, the way your references.tex file is set up, you're producing the bibliography manually. In latex, you can either produce a bibliography by manually listing the entries of the bibliography or producing it automatically using the bibtex or biber/biblatex with a .bib file. I tend to prefer bibtex over biblatex, but either would be preferred to the current manual references.tex style.

**Comment by katyhuff** [comment]
(anyway, it's not a problem for me, because my solution is to just ignore the references.tex file and insert bibtex instead. I'm just mentioning it because the way the references.tex file is set up is probably misleading/frustrating for beginners).

**Comment by dgalcius** [comment]
@katyhuff I'm happy you are using bibtex. I do agree that bibtex setup would be better (though I am not sure if it is easier for LaTeX beginners). Biblatex poses issues at our end during conversion process, as the output should conform to Elsevier DTD (xml output).  I'll amend template setup for bibtex/(biblatex) as soon as i can. Thanks.

**Comment by me10240** [comment]
> (anyway, it's not a problem for me, because my solution is to just ignore the references.tex file and insert bibtex instead. I'm just mentioning it because the way the references.tex file is set up is probably misleading/frustrating for beginners).
@katyhuff : Could you tell me what files do I need to change so that I can use bibtex too ?

**Comment by katyhuff** [comment]
It's been a few years now, but....

### option 1: Edit References.tex
Instead of the content currently in references.tex, include the following:

```
\chapter*{References}
\end{frontmatter}

  \bibliographystyle{dinat}
  \bibliography{2018-hybrid-book}
```


### option 2: Ignore References.tex
Alternatively, in the book.tex file, replace:
```
\Backmatter
  \include{references}
\end{document}
```
with:

```
\Backmatter
  \bibliographystyle{plain}
  \bibliography{2018-hybrid-book}
\end{document}
```


### Either way
In the new scenario in both cases, you reference a .bib file from whence to source the bibliography. You'll want to create such a .bib file. Name it whatever you put as the name (where I have 2018-hybrid-book, put the name of your file.). I create my .bib files automatically with a reference manager. I use Zotero, but you can use anything (mendeley, endnote, refworks, whatever...)

Additionally, you'll need to compile the document with bibtex included, like so (or similar):

```
latex book
bibtex book
latex book
latex book
dvipdf book
```

or, alternatively
```
pdflatex book
bibtex book
pdflatex book
pdflatex book
```

**Comment by dgalcius** [comment]
@katyhuff  Agreed. I have updated the template slightly. Basically I commented out the reference section. Now author can choose what to use:  bibtex, biblatex or plain latex. 
Thanks for reminding me about the issue.

**Comment by katyhuff** [comment]
Excellent, nice work! This issue can probably be closed then! (I don't have permission to do that, so it'll be up to you @dgalcius )

**Comment by dgalcius** [comment]
The _natbib_ package is moved from the class to the .tex template file. This way author can replace _natbib_ with _biblatex_ if needed.
